spring.threads.virtual.enabled: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/micro-service
    username: postgres
    password: sajal1230
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

queue:
  order-create: ORDER_CREATED_EVENT
  billed-order: BILLED_ORDER_EVENT
  refund-payment: REFUND_PAYMENT_EVENT
  order-canceled: ORDER_CANCELED_EVENT

server:
  port: 8082
